-- Add missing job sheet columns
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "leadSource" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "onlineBooking" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "expensesTotal" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "timeTracked" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "labourCostTotal" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "lineItemCostTotal" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "totalCosts" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "quoteDiscount" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "totalRevenue" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "profit" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "profitPercent" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "replied" TEXT;
